### ISSUE TITLE
ubar, vbar

### ISSUE THREAD

**Issue by daviddritschel** [matt-frey/epic#258]
https://github.com/matt-frey/epic/blob/9c67f271dbb83e110df375a0cc420cf3a5033655/src/3d/inversion/inversion.f90#L41

We could extend cs to -1:nz+1 and fft the whole of vortg(3,...), then calculate its z derivative by second order differentiation over iz = 0 to nz instead of using the boundary derivatives in the present code.  This would be more compact and consistent, as we currently don't use the extrapolated vorticity

Also, on line 133, ubar,vbar have zero values at z = 0 while in 2D we remove the mean value to have zero net momentum.  The tri-diag MPIC code I have has the lines

ubar(0)=zero                                                                    
vbar(0)=zero                                                                    
do iz=0,nz-1                                                                    
  ubar(iz+1)=ubar(iz)+dz2*(es(1,1,iz)+es(1,1,iz+1))                             
  vbar(iz+1)=vbar(iz)-dz2*(ds(1,1,iz)+ds(1,1,iz+1))                             
enddo                                                                           
uavg=fnvgpi*sum(ubar(1:nz-1)+f12*ubar(nz))                                      
vavg=fnvgpi*sum(vbar(1:nz-1)+f12*vbar(nz))                                      
do iz=0,nz                                                                      
  ubar(iz)=ubar(iz)-uavg                                                        
  vbar(iz)=vbar(iz)-vavg                                                        
enddo                                                                           

SO I think we need to take away this average in EPIC too.

**Comment by matt-frey** [comment]
@daviddritschel What are `fnvgpisum`, `f12ubar` and `f12vbar`?

**Comment by matt-frey** [comment]
Shouldn`t this read `f12 * ubar` instead?
