### ISSUE TITLE
Revisit physical constants and parameters

### ISSUE THREAD

**Issue by matt-frey** [matt-frey/epic#269]
We should go through all the physical constants and parameters and agree on a naming scheme. We should further decide which quantities are modifiable or non-modifiable.

**Comment by sjboeing** [comment]
Agreed: I think there are differences between the "moist setup" and the the "main parameters" at the moment.

**Comment by sjboeing** [comment]
@matt-frey: I suggest removing the duplicate parameter theta_l0, from the moist setup, and just using the physical constant here. It actually looks like PMPIC and MPIC have just slightly different choices for theta_l0 and some of the other parameters. My suggestion would be to use q0 to make the choice consistent with either MPIC or PMPIC. For PMPIC, I now have a few large reference runs, so maybe consistency with pmpic is best? 
I also wonder if it is confusing to have the separate phys_parameters.f90 'hidden' in the 3D utils, rather than the general utils. What do you think?

**Comment by matt-frey** [comment]
Yes, we can move `phys_parameters.f90` to just `src/utils`. I am not so familiar with the choice of parameters in this scientific area (except maybe of obvious values like gravity), whatever you think is best.

**Comment by sjboeing** [comment]
Sounds good. I think it will make things clearer, we may also want to have MPIC physics in 2D, which would make for a very nice movie of a 2D cloud.
I would suggest to keep the condensation length scale (or its inverse lam_c) and q0 as namelist parameters for MPIC cases.  theta_0 could also be a namelist parameter. One question is how to ensure consistency between parameters used in "models" and in the main code. One option for this would be to include these parameters in the initialisation file for MPIC-like cases. Apologies, it may take me a bit longer to actually do this as I am at the Met Office this week.

**Comment by matt-frey** [comment]
We could also write these physical parameters to NetCDF when creating the model. EPIC could these values in, like we do with fields (or parcels) for initialisation.

**Comment by sjboeing** [comment]
Yes, that sounds good!

**Comment by matt-frey** [comment]
I also just talked with David about these parameters. He said we should take the values used in the publication.

**Comment by matt-frey** [comment]
Ok. So then there are two options. We use either the same values as in the MPIC paper and then change to MONC's value later or we use MONC's values from the beginning and the state in the paper that they differ from the original MPIC paper.

**Comment by sjboeing** [comment]
However, I think we can choose the values of the "non-physical" parameters (theta_0, q_0 and lambda_c) such that we effectively recover equivalent equations to those we used in either MPIC or PMPIC (MPIC and PMPIC are not exactly the same), because not all parameters are independent.

**Comment by sjboeing** [comment]
I will make a table with suggested values

**Comment by sjboeing** [comment]
|  			   			 		                       |  			 MPIC/PMPIC 		                                                |  			 MONC 		    |  			 Suggested 			EPIC type 		 |  			 Suggested 			EPIC value 		                       |
|-----------------------------|--------------------------------------------------------------|------------|------------------------|-----------------------------------------------|
|  			 Parameters 		               |  			   			 		                                                        |  			   			 		      |  			   			 		                  |  			   			 		                                         |
|  			 c_pd 		                     |  			 (1000) 		                                                    |  			 1005.0 		  |  			 Constant 		            |  			 1005.0 		                                     |
|  			 rlvap 		                    |  			 (2500000) 		                                                 |  			 2.501e6 		 |  			 Constant 		            |  			 2.501e6 		                                    |
|  			 Grav 		                     |  			 (absorbed 			into time scale, but assumed to be 10 here) 		     |  			 9.81 		    |  			 Constant 		            |  			 9.81 		                                       |
|  			 Lambda 			 			 		                 |  			 (absorbed 			into height scale, but assumed to be 1000 here) 		 |  			 n/a 		     |  			 “Models” 			parameter 		  |  			 1000.*(10/9.81)=1019.367991845056 		          |
|  			 Theta_0 			 			 		                |  			 (300) 		                                                     |  			 varies 		  |  			 “Models” 			parameter 		  |  			 (rlvap*q_0)/(0.125*c_pd)=298.6268656716418 		 |
|  			 q_0 			 			 		                    |  			 (0.015) 		                                                   |  			 n/a 		     |  			 “Models” 			parameter 		  |  			 0.015 		                                      |
|  			 dtheta_bubble 			[K] 		        |  			 3 		                                                         |  			   			 		      |  			   			 		                  |  			 2.986268656716418 		                          |
|  			   			 		                       |  			   			 		                                                        |  			   			 		      |  			   			 		                  |  			   			 		                                         |
|  			 Combinations 		             |  			   			 		                                                        |  			   			 		      |  			   			 		                  |  			   			 		                                         |
|  			 rlvap*q_0/(c_pd*theta_0) 		 |  			 0.125 		                                                     |  			   			 		      |  			   			 		                  |  			 0.125 		                                      |
|  			 dtheta_bubble/theta_0 		    |  			 0.01 		                                                      |  			   			 		      |  			   			 		                  |  			 0.01 		                                       |
|  			 g*fdthetal0*lambda 		       |  			 100 		                                                       |  			   			 		      |  			   			 		                  |  			  100 		                                       |

**Comment by sjboeing** [comment]
Note that the domain size scales with lambda

**Comment by sjboeing** [comment]
Meanwhile found PMPIC is consistent with MPIC, it does not use the MONC parameters.

**Comment by sjboeing** [comment]
I thought consistency with the dimensional version of MONC would be best moving forward, so that we can have a fair comparison. Possibly we can make all of these namelist-readable, with the MONC values as defaults. I thought the values in the table above would give the greatest consistency in the easiest way (with dimentional time 100s corresponding to dimensionless time 1, although it does mean the scaling/domain height ends up being  a slightly awkward number). The alternative would be to use a different q_0.

**Comment by matt-frey** [comment]
I suggest we put them into a group in NetCDF. For the moist setup this could like this:
```
group: physical_constants {

  // group attributes:
                :q_0 = 0.015 ;
                :theta_l0 = 288. ;
                :g  = 9.81 ;
                :L_v = 2501000. ;
                :c_p = 1005. ;
  } // group parameters
}
```
We should however use standard names, i.e. `gravity` instead of just `g`.

**Comment by matt-frey** [comment]
I agree to both.

**Comment by matt-frey** [comment]
I just realized that when we read them we cannot use the keyword `parameter` to make a constant in Fortran, of course.

**Comment by matt-frey** [comment]
There seems to be some sort of solution with the keyword `protetcted` (Fortran 2003). The value of the variable cannot be modified outside the module, see also https://stackoverflow.com/questions/15020460/protected-global-variables-in-fortran. I think we should go for this.

**Comment by daviddritschel** [comment]
That sounds like a good solution
