### ISSUE TITLE
Interface to NetCDF

### ISSUE THREAD

**Issue by matt-frey** [matt-frey/epic#271]
The atmospheric community uses NetCDF (https://www.unidata.ucar.edu/software/netcdf/) following the CF (climate forecast) convention (https://cfconventions.org/).

**Comment by sjboeing** [comment]
I may write a Python script to do the conversion of the fields data for now. Providing (distinct) dimension labels on the hdf5 data could also help to explore this data with ncview, although it would be easiest to have the different "steps" in a time dimension for ncview exploration.

**Comment by sjboeing** [comment]
Added the temporary script (for fields) to the moist_test_debug branch. Can probably use some more work.
