### ISSUE TITLE
Non-centered domains in x and y

### ISSUE THREAD

**Issue by sjboeing** [matt-frey/epic#277]
These are currently giving issues.

**Comment by matt-frey** [comment]
I can confirm that there is an issue for non-centred domains. The currently formula is
```
xnew = x - L * int((x - c) / L)
```
Example: A domain from 0 to 1; hence `L = 1` and `c = 0.5`. We place the parcel  outside the domain at `x = 1.25`. The parcel should end up at `xnew = 0.25`. However, we get
```
xnew = 1.25 - 1 * int((1.25 - 0.5) / 1) = 1.25 - int(0.75) = 1.25 - 0 = 1.25.

**Comment by matt-frey** [comment]
If we remove the shift by `c`, we get the correct result for this example.

**Comment by matt-frey** [comment]
It doesn't work with a domain from -0.5 to 1 and parcel placed at 1.25.

**Comment by matt-frey** [comment]
I just realized that I forgot at factor two in the first equation. The position correction is acutally given by
```
xnew = x - L * int(2 * (x - c) / L)
```
The first example yields therefore the correct result of `xnew = 0.25`, as shown here:
```
xnew = 1.25 - 1 * int(2 * (1.25 - 0.5)) = 1.25 - int(1.5) = 1.25 - 1 = 0.25.
```
The example with a domain from -0.5 to 1 is correct as well:
```
xnew = 1.25 - 1.5 * int(2 * (1.25 - 0.25) / 1.5) = 1.25 - 1.5 * int(1.333...) = 1.25 - 1.5 = -0.25.
```

**Comment by matt-frey** [comment]
@sjboeing After revisiting, I do not see an issue in the way we apply the parcel BC. It works for centred and non-centred domains.

**Comment by matt-frey** [comment]
I haven't re-checked the computation of `get_delx` and `get_dely` yet.

**Comment by matt-frey** [comment]
The functions `get_delx` and `get_dely` do not work for non-centred domains, however. The functions currently read
```
delx = x1 - x2
delx = delx - L * int(2 * (delx - c) / L)
```
#### Example for a centred domain
Domain: `[-1, 1]`, (extent) `L = 2`, (centre) `c = 0`
Assuming `x1 = -0.9` and `x2 = 0.8`, then
```
delx = -0.9 - 0.8 = -1.7
-1.7 - 2 * int(2 * (-1.7) / 2) = -1.7 - 2 * int(-1.7) = -1.7 + 2 = 0.3
```
If `x1 = 0.8` and `x2 = -0.9`, we get `delx = -0.3` instead.

#### Example for a non-centred domain
Domain: `[0, 1]`, (extent) `L = 1`, (centre) `c = 0.5`
Assuming `x1 = 0.1` and `x2 = 0.9`, then
```
delx = 0.1 - 0.9 = -0.8
-0.8 - 1 * int(2 * (-0.8 - 0.5) / 1) = -0.8 - int(-2.6) = -0.8 + 2 = 1.2
```
If `x1 = 0.9` and `x2 = 0.1`, we get `delx = 0.8` instead.

### Solution
I think the shift by the centre (in above non-centred domain example `c = 0.5`) is wrong. If we don't do this, i.e.
```
delx = x1 - x2
delx = delx - L * int(2 * delx / L)
```
we get
```
delx = 0.1 - 0.9 = -0.8
-0.8 - 1 * int(2 * (-0.8) / 1) = -0.8 - int(-1.6) = -0.8 + 1 = 0.2
```
and
```
delx = 0.9 - 0.1 = 0.8
0.8 - 1 * int(2 * 0.8 / 1) = 0.8 - int(1.6) = 0.8 - 1 = -0.2
```
instead.
