### ISSUE TITLE
add topics cfd, particle-in-cell

### ISSUE THREAD

**Issue by Beliavsky** [matt-frey/epic#307]
I suggest adding the topics cfd, particle-in-cell in the About section.

Thanks for your project -- I have added it to the Computational Fluid Dynamics section of my [list of Fortran codes](https://github.com/Beliavsky/Fortran-code-on-GitHub).

**Comment by matt-frey** [comment]
@Beliavsky Hi, thanks a lot. Yes, we will update the About section.

**Comment by matt-frey** [comment]
Suggested topics are added. I'll close this issue.
