### ISSUE TITLE
Theory for Vmin/Vmax in 3D

### ISSUE THREAD

**Issue by sjboeing** [matt-frey/epic#347]
Work out in terms of both distance between split parcels (along major axis) and support points (along the major-middle diagonal).

From slack: I was thinking about the dynamic size range a bit more, in particular with regard to a simple conceptual model that generates a distribution that can then be compared to a distribution once we reach splitting/merging equilibrium. One simple conceptual model is a set of “parcels” (with no information on e.g. location of parcels given, just a set of random objects with a given volume) that split with a certain probability each time step, and merge with a random other parcel once below Vmin (in the limit of a small time step). We can also add a Vmax to this. Could be interesting to compare against EPIC.

**Comment by matt-frey** [comment]
Vmin: 1/40
Vmax: 1/5

**Comment by sjboeing** [comment]
Closing this issue, as this will be documented in the 3D paper.
