### ISSUE TITLE
Ensure pe_ref not calculated upon restart

### ISSUE THREAD

**Issue by sjboeing** [matt-frey/epic#421]
I think currently this is recalculated, which can be quite expensive for larger runs.

**Comment by matt-frey** [comment]
Yes, indeed. We would need to write `pe_ref` to the NetCDF file and check if it is available upon restart and then read the value.

**Comment by matt-frey** [comment]
We may add this as a global attribute to the diagnostics NetCDF. Not sure if this is the best location inside the NetCDF though.
